import { db } from "@/db";
import {
  users,
  products,
  courses,
  courseSessions,
  siteSettings,
  gameScores,
  notifications,
  reviews,
} from "@/db/schema";
import { hashPassword } from "@/lib/auth";
import { count } from "drizzle-orm";

export async function runSeed() {
  // Check if already seeded
  const [{ value: userCount }] = await db.select({ value: count() }).from(users);
  if (Number(userCount) > 0) {
    return { status: "already_seeded" };
  }

  // 1. Create Admin & User
  const adminPasswordHash = await hashPassword("Amir@Digitalist2026!");
  const userPasswordHash = await hashPassword("User@123456");

  const [adminUser] = await db
    .insert(users)
    .values([
      {
        email: "1388amiralian@gmail.com",
        name: "هکر امیر",
        passwordHash: adminPasswordHash,
        role: "admin",
        phone: "09308625900",
        avatar: "/images/haker-amir.jpg",
      },
      {
        email: "user@digitalist.ir",
        name: "کاربر نمونه دیجیتالیست",
        passwordHash: userPasswordHash,
        role: "user",
        phone: "09121112233",
        avatar: "https://images.pexels.com/photos/6804612/pexels-photo-6804612.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=200&w=280",
      },
    ])
    .returning();

  // 2. Site Settings
  await db.insert(siteSettings).values([
    { key: "brand_name", value: "دیجیتالیست" },
    { key: "owner_name", value: "هکر امیر" },
    { key: "slogan", value: "تکنولوژی، آموزش و خلاقیت؛ در یک تجربه دیجیتال." },
    { key: "phone", value: "09308625900" },
    { key: "telegram_title", value: "Violinist🎻🎵" },
    { key: "telegram_url", value: "https://t.me/amirgraph" },
    { key: "instagram_title", value: "amirgraph" },
    { key: "instagram_url", value: "https://instagram.com/amirgraph" },
    { key: "email", value: "1388amiralian@gmail.com" },
    {
      key: "hero_subtitle",
      value: "با هکر امیر، دنیای تکنولوژی، آموزش و موسیقی را تجربه کن.",
    },
    {
      key: "about_bio",
      value:
        "من هکر امیر هستم؛ متخصص فناوری، برنامه‌نویس، طراح خلاق، مدرس نرم‌افزارهای دیجیتال و نوازنده ویولن. برند دیجیتالیست پلی است میان دنیای دقیق و قدرتمند سخت‌افزار، جادوی کدنویسی و لطافت بی‌پایان موسیقی. اینجا مکانی برای کسانی است که به کمال مهندسی و هنر عشق می‌ورزند.",
    },
  ]);

  // 3. Products
  const seedProducts = [
    {
      slug: "gaming-pc-digitalist-titan",
      name: "کیس گیمینگ فوق‌حرفه‌ای دیجیتالیست تایتان (Core i9 14900K / RTX 4090 / 64GB DDR5)",
      nameEn: "Digitalist Titan Extreme Gaming PC",
      category: "computer",
      categoryName: "کامپیوتر کامل",
      price: 195000000,
      originalPrice: 215000000,
      discountPercent: 9,
      stock: 4,
      image: "https://images.pexels.com/photos/11047223/pexels-photo-11047223.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      gallery: JSON.stringify([
        "https://images.pexels.com/photos/11047223/pexels-photo-11047223.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        "https://images.pexels.com/photos/34552804/pexels-photo-34552804.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        "https://images.pexels.com/photos/32973378/pexels-photo-32973378.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      ]),
      shortDescription: "شاهکار پردازش و رندرینگ با پردازنده اینتل Core i9 14900K و کارت گرافیک RTX 4090 24GB و خنک‌کننده مایع سفارشی.",
      description: "سیستم گیمینگ و ورک‌استیشن دیجیتالیست تایتان برای بالاترین سطح گیمینگ 4K، رندرینگ سنگین در پریمیر، افتر افکت، بلندر و شبیه‌سازی‌های هوش مصنوعی طراحی شده است. تمام قطعات نو با گارانتی اصلی ارائه می‌شوند.",
      specs: JSON.stringify({
        "پردازنده": "Intel Core i9 14900K (24 هسته، تا 6.0 گیگاهرتز)",
        "کارت گرافیک": "ASUS ROG Strix GeForce RTX 4090 24GB GDDR6X",
        "مادربرد": "ASUS ROG MAXIMUS Z790 HERO",
        "حافظه رم": "Corsair Dominator Titanium 64GB (2x32GB) DDR5 6400MHz",
        "حافظه داخلی": "Samsung 990 PRO 2TB NVMe M.2 PCIe Gen4",
        "منبع تغذیه": "Corsair RM1200x SHIFT 1200W 80 Plus Gold",
        "خنک‌کننده": "NZXT Kraken Elite 360 RGB Liquid Cooler",
        "کیس": "Lian Li O11 Dynamic EVO RGB Black Edition",
      }),
      tags: JSON.stringify(["کامپیوتر گیمینگ", "RTX 4090", "ورک‌استیشن", "هوش مصنوعی"]),
      rating: "5.0",
      reviewCount: 7,
      isFeatured: true,
      isNew: true,
    },
    {
      slug: "gpu-rtx-4080-super",
      name: "کارت گرافیک ایسوس ROG Strix GeForce RTX 4080 Super 16GB OC Edition",
      nameEn: "ASUS ROG Strix RTX 4080 Super 16GB",
      category: "components",
      categoryName: "قطعات کامپیوتر",
      price: 89000000,
      originalPrice: 94000000,
      discountPercent: 5,
      stock: 8,
      image: "https://images.pexels.com/photos/34552804/pexels-photo-34552804.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      gallery: JSON.stringify([
        "https://images.pexels.com/photos/34552804/pexels-photo-34552804.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        "https://images.pexels.com/photos/34552810/pexels-photo-34552810.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      ]),
      shortDescription: "قدرت بی‌رقیب پردازش گرافیکی با فناوری DLSS 3.5، ری‌تریسینگ نسل سوم و طراحی خنک‌کننده ۳ فن آکسیال.",
      description: "کارت گرافیک RTX 4080 Super گزینه‌ای بی‌نظیر برای گیمرهای جدی و ادیتورهای حرفه‌ای است که می‌خواهند بدون محدودیت و با نهایت فریم‌ریت، سنگین‌ترین بازی‌ها و پروژه‌های پریمیر و داوینچی را رندر کنند.",
      specs: JSON.stringify({
        "حافظه گرافیکی": "16GB GDDR6X",
        "باس حافظه": "256 بیت",
        "هسته‌های کودا": "10240 Cores",
        "پورت‌ها": "2x HDMI 2.1a, 3x DisplayPort 1.4a",
        "توان پیشنهادی پاور": "850 وات",
        "نورپردازی": "Aura Sync ARGB",
      }),
      tags: JSON.stringify(["کارت گرافیک", "انویدیا", "ASUS", "قطعات کامپیوتر"]),
      rating: "4.9",
      reviewCount: 12,
      isFeatured: true,
      isNew: true,
    },
    {
      slug: "laptop-asus-rog-strix-scar-16",
      name: "لپ‌تاپ گیمینگ ایسوس ROG Strix SCAR 16 (Core i9 14900HX / RTX 4080 / 32GB / 1TB / Mini-LED 240Hz)",
      nameEn: "ASUS ROG Strix SCAR 16 G634JZ",
      category: "laptop",
      categoryName: "لپ‌تاپ",
      price: 168000000,
      originalPrice: 175000000,
      discountPercent: 4,
      stock: 5,
      image: "https://images.pexels.com/photos/28301967/pexels-photo-28301967.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      gallery: JSON.stringify([
        "https://images.pexels.com/photos/28301967/pexels-photo-28301967.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        "https://images.pexels.com/photos/28842074/pexels-photo-28842074.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      ]),
      shortDescription: "قدرتمندترین لپ‌تاپ گیمینگ ایسوس با نمایشگر خیره‌کننده ROG Nebula HDR Mini-LED 2.5K و نرخ نوسازی ۲۴۰ هرتز.",
      description: "لپ‌تاپ ایسوس ROG Strix SCAR 16 ترکیبی از نهایت قدرت پرتابل با ظاهر فوق‌مدرن و نورپردازی نئونی است. مناسب برای ادیتورهای ویدئویی، توسعه‌دهندگان نرم‌افزار و بازیکنان ورزش‌های الکترونیک.",
      specs: JSON.stringify({
        "صفحه نمایش": "16 اینچ QHD+ Mini LED 240Hz 100% DCI-P3",
        "پردازنده": "Intel Core i9 14900HX",
        "کارت گرافیک": "NVIDIA GeForce RTX 4080 12GB TGP 175W",
        "رم": "32GB DDR5 5600MHz (قابل ارتقا)",
        "حافظه SSD": "1TB PCIe 4.0 NVMe",
        "وزن": "2.65 کیلوگرم",
      }),
      tags: JSON.stringify(["لپ‌تاپ گیمینگ", "ایسوس ROG", "Mini LED", "RTX 4080"]),
      rating: "5.0",
      reviewCount: 9,
      isFeatured: true,
      isNew: true,
    },
    {
      slug: "monitor-samsung-odyssey-oled-g9",
      name: "مانیتور گیمینگ سامسونگ Odyssey OLED G9 سایز ۴۹ اینچ خمیده 240Hz",
      nameEn: "Samsung Odyssey OLED G9 49-inch Curved Gaming Monitor",
      category: "monitor",
      categoryName: "مانیتور",
      price: 112000000,
      originalPrice: 120000000,
      discountPercent: 7,
      stock: 3,
      image: "https://images.pexels.com/photos/37848029/pexels-photo-37848029.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      gallery: JSON.stringify([
        "https://images.pexels.com/photos/37848029/pexels-photo-37848029.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        "https://images.pexels.com/photos/3829227/pexels-photo-3829227.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      ]),
      shortDescription: "افق دید بی‌پایان با پنل OLED کوانتوم دات، نسبت تصویر 32:9 و زمان پاسخ‌دهی شگفت‌انگیز 0.03 میلی‌ثانیه.",
      description: "با مانیتور ۴۹ اینچی سامسونگ ادیسی OLED G9 در دنیای بازی‌ها و تایم‌لاین‌های چند لایه پریمیر غرق شوید. دو نمایشگر QHD در قالب یک پنل یکپارچه با کیفیت رنگ خیره‌کننده.",
      specs: JSON.stringify({
        "اندازه صفحه": "49 اینچ فوق عریض 32:9",
        "نوع پنل": "OLED Curved 1800R",
        "رزولوشن": "5120x1440 (Dual QHD)",
        "نرخ نوسازی": "240Hz",
        "زمان پاسخ‌دهی": "0.03ms (GtG)",
        "پوشش رنگ": "99% DCI-P3",
      }),
      tags: JSON.stringify(["مانیتور", "سامسونگ", "OLED", "گیمینگ"]),
      rating: "4.8",
      reviewCount: 15,
      isFeatured: false,
      isNew: true,
    },
    {
      slug: "keyboard-custom-digitalist-wireless",
      name: "کیبورد مکانیکال سفارشی بی‌سیم دیجیتالیست پرو با سوییچ‌های سایلنت لواندر",
      nameEn: "Digitalist Pro Custom Wireless Mechanical Keyboard",
      category: "gaming",
      categoryName: "تجهیزات گیمینگ",
      price: 14500000,
      originalPrice: 16000000,
      discountPercent: 9,
      stock: 12,
      image: "https://images.pexels.com/photos/13162096/pexels-photo-13162096.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      gallery: JSON.stringify([
        "https://images.pexels.com/photos/13162096/pexels-photo-13162096.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      ]),
      shortDescription: "بدنه تمام آلومینیوم CNC، ساختار گسکت مونت با فوم‌های سایلنت، اتصال ۳ حالته و هات‌سواپ ۵ پین.",
      description: "طراحی اختصاصی هکر امیر برای برنامه‌نویسان و تایپیست‌های حرفه‌ای که دنبال صدایی آرامش‌بخش (Thock) و دقت کلیدها در تایپ طولانی هستند.",
      specs: JSON.stringify({
        "نوع اتصال": "بلوتوث 5.2 / دانگل 2.4Ghz / کابل Type-C",
        "باتری": "4000mAh لیتیومی با ماندگاری تا ۲۰۰ ساعت",
        "سوییچ‌ها": "Custom Factory Lubed Linear Lavender",
        "کلیدها": "PBT Doubleshot Cherry Profile فارسی و انگلیسی",
      }),
      tags: JSON.stringify(["کیبورد مکانیکال", "سفارشی", "گیمینگ", "کدنویسی"]),
      rating: "5.0",
      reviewCount: 18,
      isFeatured: true,
      isNew: true,
    },
    {
      slug: "liquid-cooler-360-digital-display",
      name: "خنک‌کننده مایع پردازنده دیپ‌کول LD360 با نمایشگر دیجیتال دما و وات",
      nameEn: "DeepCool LD360 Digital AIO Liquid Cooler",
      category: "accessories",
      categoryName: "لوازم جانبی",
      price: 8800000,
      originalPrice: 9500000,
      discountPercent: 7,
      stock: 10,
      image: "https://images.pexels.com/photos/32991895/pexels-photo-32991895.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      gallery: JSON.stringify([
        "https://images.pexels.com/photos/32991895/pexels-photo-32991895.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      ]),
      shortDescription: "رادیاتور ۳۶۰ میلی‌متری با ۳ فن PWM بی‌صدا و نمایشگر بلادرنگ دمای لحظه‌ای CPU روی پمپ آب.",
      description: "خنک‌کننده‌ای پیشرفته با تکنولوژی ضد نشت اختصاصی که خیال شما را از کنترل دمای سنگین‌ترین پردازنده‌های نسل ۱۴ و رایزن ۹۰۰۰ راحت می‌کند.",
      specs: JSON.stringify({
        "اندازه رادیاتور": "360mm",
        "تعداد فن": "3x 120mm Fluid Dynamic Bearing",
        "نمایشگر": "Real-time CPU Temperature & Wattage Display",
        "سازگاری": "LGA1700/1851 و AM4/AM5",
      }),
      tags: JSON.stringify(["خنک‌کننده", "خنک‌کننده مایع", "قطعات"]),
      rating: "4.7",
      reviewCount: 6,
      isFeatured: false,
      isNew: true,
    },
    // VIOLINS & ACCESSORIES
    {
      slug: "violin-master-stradivari-cremona-handcrafted",
      name: "ویولن مستر دست‌ساز مدل استرادیواری کرمونا ۴/۴ با چوب افرا و اسپیروس اروپایی کهنه‌کاری شده",
      nameEn: "Master Handcrafted Cremona Stradivarius Model 4/4 Violin",
      category: "violin",
      categoryName: "ویولن تخصصی",
      price: 48000000,
      originalPrice: 54000000,
      discountPercent: 11,
      stock: 2,
      image: "https://images.pexels.com/photos/306175/pexels-photo-306175.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      gallery: JSON.stringify([
        "https://images.pexels.com/photos/306175/pexels-photo-306175.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        "https://images.pexels.com/photos/25859077/pexels-photo-25859077.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        "https://images.pexels.com/photos/6664578/pexels-photo-6664578.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        "https://images.pexels.com/photos/5137409/pexels-photo-5137409.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      ]),
      shortDescription: "انتخاب شخصی هکر امیر برای کنسرت‌ها و ضبط استودیویی؛ ساخته شده از چوب‌های طبیعی با قدمت بالای ۱۵ سال با صدایی گرم، عمیق و طنین‌انداز.",
      description: "این ساز دست‌ساز بی‌نظیر مطابق با الگوی مشهور آنتونیو استرادیواری ۱۷۱۶ ساخته شده است. صفحه رویی از صنوبر باکیفیت و صفحه پشتی و کلاف از افرای موج‌دار برگزیده اروپایی است. ساز پیش از ارسال توسط هکر امیر رگلاژ، تست صدایی و کوک دقیق می‌شود.",
      specs: JSON.stringify({
        "سایز": "۴/۴ استاندارد بزرگسال",
        "صفحه رویی": "Spruce اروپایی دست‌چین با رگه‌های یکنواخت",
        "صفحه زیر و کلاف": "Flamed Maple رگه‌دار اروپایی",
        "گریف و گوشی‌ها": "آبنوس درجه یک ماداگاسکار (Ebony)",
        "پل و خرک": "خرک فرانسوی Aubert Mirecourt اصل",
        "سیم‌ها": "ست سیم‌های Thomastik Dominant اتریش",
        "لوازم همراه": "آرشه کربن فایبر مستر، کلیفون آلمانی و هاردکیس لوکس",
      }),
      tags: JSON.stringify(["ویولن", "دست‌ساز", "استرادیواری", "ویولن حرفه‌ای"]),
      rating: "5.0",
      reviewCount: 14,
      isFeatured: true,
      isNew: true,
    },
    {
      slug: "violin-yamaha-v5-sc-starter",
      name: "ویولن یاماها Yamaha V5-SC سایز ۴/۴ به همراه آرشه، کلیفون و هاردکیس",
      nameEn: "Yamaha V5-SC 4/4 Acoustic Student Violin Outfit",
      category: "violin",
      categoryName: "ویولن تخصصی",
      price: 24500000,
      originalPrice: 26500000,
      discountPercent: 8,
      stock: 6,
      image: "https://images.pexels.com/photos/5137409/pexels-photo-5137409.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      gallery: JSON.stringify([
        "https://images.pexels.com/photos/5137409/pexels-photo-5137409.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        "https://images.pexels.com/photos/7095503/pexels-photo-7095503.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      ]),
      shortDescription: "بهترین انتخاب اساتید موسیقی برای هنرجویان متد سوزوکی با ساخت یکدست، کوک پایدار و صدادهی شفاف و پر انرژی.",
      description: "ویولن یاماها V5 استاندارد طلایی شروع آموزش ویولن در سراسر جهان است. با گریف چوب آبنوس و خرک رگلاژ شده، هنرجو با راحتی کامل به فراگیری پوزیسیون‌ها و آرشه‌کشی می‌پردازد.",
      specs: JSON.stringify({
        "برند": "یاماها (Yamaha)",
        "سایز": "۴/۴",
        "صفحه رو": "اسپیروس (صنوبر)",
        "صفحه پشت": "افرا (Maple)",
        "گریف": "آبنوس (Ebony)",
        "تاندور": "۴ تاندور سرخود ویتنر آلمان",
      }),
      tags: JSON.stringify(["ویولن یاماها", "آموزش ویولن", "ساز اصیل"]),
      rating: "4.9",
      reviewCount: 22,
      isFeatured: false,
      isNew: true,
    },
    {
      slug: "violin-bow-carbon-fiber-pro",
      name: "آرشه ویولن کربن فایبر با موی طبیعی اسب مغولی و پاشنه آبنوس صدف‌کاری",
      nameEn: "Professional Carbon Fiber Violin Bow 4/4",
      category: "violin_accessories",
      categoryName: "لوازم ویولن",
      price: 3800000,
      originalPrice: 4200000,
      discountPercent: 10,
      stock: 15,
      image: "https://images.pexels.com/photos/37210790/pexels-photo-37210790.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      gallery: JSON.stringify([
        "https://images.pexels.com/photos/37210790/pexels-photo-37210790.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      ]),
      shortDescription: "تعادل آیرودینامیک بی‌نقص، انعطاف‌پذیری ایده‌آل برای تکنیک‌های اسپیکاتو و استاکاتو بدون شکستگی یا تاب‌خوردگی.",
      description: "آرشه کربن فایبر حرفه‌ای با وزن ایده‌آل ۶۰ گرم و نقطه تعادل دقیق، به دست نوازنده استقامت و پاسخ‌دهی شگفت‌انگیزی در قطعات سرعتی می‌بخشد.",
      specs: JSON.stringify({
        "جنس چوبک": "الیاف کربن مشبک درجه یک",
        "موی آرشه": "موی دم اسب سفید مغولی دست‌چین",
        "پاشنه (Frog)": "چوب آبنوس ماداگاسکار با نگین صدف ابالون",
        "وزن": "۶۰.۵ گرم",
      }),
      tags: JSON.stringify(["آرشه ویولن", "کربن فایبر", "لوازم جانبی ویولن"]),
      rating: "5.0",
      reviewCount: 11,
      isFeatured: false,
      isNew: true,
    },
    {
      slug: "violin-strings-pirastro-evah-pirazzi-gold",
      name: "ست سیم ویولن پیراسترو مدل اوا پیرازی گلد اصل آلمان (سیم می پلاتینیوم)",
      nameEn: "Pirastro Evah Pirazzi Gold Violin String Set (Platinum E)",
      category: "violin_accessories",
      categoryName: "لوازم ویولن",
      price: 4950000,
      originalPrice: 5500000,
      discountPercent: 10,
      stock: 20,
      image: "https://images.pexels.com/photos/6664578/pexels-photo-6664578.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      gallery: JSON.stringify([
        "https://images.pexels.com/photos/6664578/pexels-photo-6664578.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      ]),
      shortDescription: "محبوب‌ترین سیم‌های نوازندگان برجسته کنسرت‌های جهانی؛ حجم صدایی باورنکردنی، پایداری کوک آنی و گرمای تنالیته استثنایی.",
      description: "سیم‌های پیراسترو اوا پیرازی گلد اوج تکنولوژی هسته مصنوعی مدرن در کنار روکش‌های نقره و پلاتینیوم هستند که داینامیک صدای ساز شما را چند برابر می‌کنند.",
      specs: JSON.stringify({
        "کشور سازنده": "آلمان (Offenbach)",
        "سیم می (E)": "استیل با روکش پلاتینیوم",
        "سیم لا (A)": "هسته مصنوعی با روکش آلومینیوم",
        "سیم ر (D)": "هسته مصنوعی با روکش نقره خالص",
        "سیم سل (G)": "هسته مصنوعی با روکش طلا ۲۴ عیار",
      }),
      tags: JSON.stringify(["سیم ویولن", "پیراسترو", "اوا پیرازی", "لوازم ویولن"]),
      rating: "5.0",
      reviewCount: 24,
      isFeatured: true,
      isNew: true,
    },
  ];

  for (const prod of seedProducts) {
    await db.insert(products).values(prod);
  }

  // 4. Educational Courses
  const seedCourses = [
    {
      slug: "photoshop-masterclass-2026",
      title: "مسترکلاس جامع فتوشاپ ۲۰۲۶؛ از صفر تا طراحی تخصصی و آرت دیجیتال",
      titleEn: "Photoshop Pro Masterclass 2026",
      category: "photoshop",
      instructor: "هکر امیر",
      price: 1850000,
      originalPrice: 2400000,
      discountPercent: 23,
      image: "https://images.pexels.com/photos/37848029/pexels-photo-37848029.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      previewVideoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      shortDescription: "آموزش کامل ابزارهای ادوبی فتوشاپ، تلفیق هوش مصنوعی Firefly، روتوش چهره، پوسترسازی و طراحی کاورهای مینیمال مدرن.",
      description: "این دوره با نگاه متفاوتی به دنیای گرافیک طراحی شده است. از صفر مطلق و تسلط بر لایه‌ها، ماسک‌ها و ابزارهای برش، تا پیشرفته‌ترین تکنیک‌های ترکیب تصاویر (Photo Manipulation)، اصلاح رنگ سینمایی، طراحی هویت بصری و ساخت بنرهای تبلیغاتی پربازده برای اینستاگرام و وب. تمام فایل‌های PSD پروژه‌ها در اختیار شما قرار می‌گیرد.",
      level: "مقدماتی تا فوق‌حرفه‌ای",
      durationHours: 24,
      sessionsCount: 16,
      prerequisites: "علاقه‌مندی به هنر دیجیتال و داشتن یک سیستم کامپیوتری معمولی",
      rating: "5.0",
      reviewCount: 38,
      isFeatured: true,
    },
    {
      slug: "premiere-pro-cinematic-editing",
      title: "دوره جامع ادوبی پریمیر پرو؛ تدوین سینمایی، موشن و جلوه‌های صوتی",
      titleEn: "Adobe Premiere Pro Cinematic Editing",
      category: "premiere",
      instructor: "هکر امیر",
      price: 2200000,
      originalPrice: 2900000,
      discountPercent: 24,
      image: "https://images.pexels.com/photos/28842074/pexels-photo-28842074.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      previewVideoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
      shortDescription: "آموزش اصول کات‌زدن ریتمیک، کالرگریدینگ حرفه‌ای با Lumetri، ترنزیشن‌های خلاقانه، تدوین ویدئوهای یوتیوب و ریلز اینستاگرام.",
      description: "در این دوره تجربیات چندین ساله تدوین و ساخت محتوای ویدیویی را به صورت گام‌به‌گام و پروژه‌محور یاد می‌گیرید. تدوین موزیک ویدیو، ساخت تیزرهای تبلیغاتی، تکنیک‌های سرعت و تایم‌رمپ، و صداگذاری با کیفیت استودیویی را کامل مسلط خواهید شد.",
      level: "مقدماتی تا پیشرفته",
      durationHours: 28,
      sessionsCount: 18,
      prerequisites: "آشنایی اولیه با کامپیوتر و نصب برنامه ادوبی پریمیر",
      rating: "4.9",
      reviewCount: 29,
      isFeatured: true,
    },
    {
      slug: "python-complete-zero-to-hero",
      title: "دوره جامع برنامه‌نویسی پایتون؛ از الفبا تا اتومیشن، هوش مصنوعی و امنیت",
      titleEn: "Complete Python Mastery: Zero to Hero",
      category: "python",
      instructor: "هکر امیر",
      price: 2900000,
      originalPrice: 3800000,
      discountPercent: 24,
      image: "https://images.pexels.com/photos/6804612/pexels-photo-6804612.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      previewVideoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
      shortDescription: "پایتون را مثل یک هکر و توسعه‌دهنده واقعی یاد بگیرید؛ سینتکس، تفکر الگوریتمی، اسکریپت‌نویسی خودکار، ساخت وب با FastAPI و مبانی امنیت شبکه.",
      description: "پایتون محبوب‌ترین و قدرتمندترین زبان برنامه‌نویسی دنیاست. در این دوره ما از مبانی متغیرها و حلقه‌ها شروع می‌کنیم، سپس شی‌گرایی را عمیق بررسی می‌کنیم و در ادامه پروژه‌های واقعی مثل ساخت ربات‌های اتومیشن، اسکرپینگ وب، ارتباط با API و ابزارهای تستی امنیتی را پیاده‌سازی می‌کنیم.",
      level: "مقدماتی تا ارشد",
      durationHours: 35,
      sessionsCount: 22,
      prerequisites: "بدون نیاز به پیش‌نیاز قبلی برنامه‌نویسی",
      rating: "5.0",
      reviewCount: 45,
      isFeatured: true,
    },
    {
      slug: "violin-suzuki-classical-method",
      title: "مسترکلاس نوازندگی ویولن؛ متد بین‌المللی سوزوکی (جلد ۱ تا ۳) و اصول آرشه‌کشی",
      titleEn: "Violin Mastery: Suzuki Classical Method Vol 1-3",
      category: "violin",
      instructor: "هکر امیر",
      price: 3400000,
      originalPrice: 4500000,
      discountPercent: 24,
      image: "https://images.pexels.com/photos/25859077/pexels-photo-25859077.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      previewVideoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
      shortDescription: "آموزش دقیق تکنیک‌های دست راست (آرشه)، دست چپ (پوزیسیون و انگشت‌گذاری)، نت‌خوانی سلفژ و اجرای قطعات ماندگار باخ، شوبرت و هندل.",
      description: "متد سوزوکی انقلابی‌ترین روش یادگیری ساز ویولن در جهان است که بر پایه شنیداری و تمرینات گام‌به‌گام استوار است. هکر امیر با سابقه نوازندگی سال‌ها ویولن، نکات کلیدی رفع فالشی، تولید صدای زنگ‌دار و تمرینات صحیح را به زبان ساده و تصویری آموزش می‌دهد.",
      level: "پایه تا متوسطه پیشرفته",
      durationHours: 30,
      sessionsCount: 20,
      prerequisites: "داشتن یک ساز ویولن سالم و حداقل ۳۰ دقیقه تمرین روزانه",
      rating: "5.0",
      reviewCount: 31,
      isFeatured: true,
    },
  ];

  for (const c of seedCourses) {
    const [inserted] = await db.insert(courses).values(c).returning();

    // Create 6-7 rich sessions for each course
    const sessions = [
      {
        courseId: inserted.id,
        orderNum: 1,
        title: `جلسه ۱: معارفه و آشنایی با نقشه راه ${c.title.split("؛")[0]}`,
        duration: "18:45",
        videoUrl: c.previewVideoUrl,
        pdfUrl: "/materials/session1-guide.pdf",
        isFreePreview: true,
        description: "بررسی ساختار دوره، نیازمندی‌ها، راه‌اندازی محیط و نصب پیش‌نیازها.",
      },
      {
        courseId: inserted.id,
        orderNum: 2,
        title: `جلسه ۲: تسلط بر اصول بنیادین و ابزارهای کلیدی`,
        duration: "32:10",
        videoUrl: c.previewVideoUrl,
        pdfUrl: "/materials/session2-cheatsheet.pdf",
        isFreePreview: false,
        description: "شروع عملیاتی، تمرین تکنیک‌های اولیه و ایجاد اولین پروژه آزمایشی.",
      },
      {
        courseId: inserted.id,
        orderNum: 3,
        title: `جلسه ۳: تکنیک‌های حرفه‌ای در سطح کاری و بازار کار`,
        duration: "41:20",
        videoUrl: c.previewVideoUrl,
        pdfUrl: "/materials/session3-assets.pdf",
        isFreePreview: false,
        description: "روش‌های استاندارد جهانی برای سرعت بخشیدن به فرایند و رعایت پرفورمنس.",
      },
      {
        courseId: inserted.id,
        orderNum: 4,
        title: `جلسه ۴: پروژه عملی جامع بخش نخست و حل چالش‌های متداول`,
        duration: "52:15",
        videoUrl: c.previewVideoUrl,
        pdfUrl: "/materials/session4-project.pdf",
        isFreePreview: false,
        description: "پیاده‌سازی یک پروژه فول از ایده اولیه تا خروجی نهایی استاندارد.",
      },
      {
        courseId: inserted.id,
        orderNum: 5,
        title: `جلسه ۵: مباحث پیشرفته، ترفندهای ناگفته هکر امیر`,
        duration: "45:00",
        videoUrl: c.previewVideoUrl,
        pdfUrl: "/materials/session5-advanced.pdf",
        isFreePreview: false,
        description: "بررسی خطاهای متداول و متدهای بهینه‌سازی که کمتر در آموزش‌ها تدریس می‌شود.",
      },
      {
        courseId: inserted.id,
        orderNum: 6,
        title: `جلسه ۶: پروژه پایانی دوره و گام‌های پس از اتمام`,
        duration: "58:30",
        videoUrl: c.previewVideoUrl,
        pdfUrl: "/materials/session6-final.pdf",
        isFreePreview: false,
        description: "جمع‌بندی پروژه نهایی، دریافت فایل‌های پیوستی، نحوه ورود به بازار کار و ارتقا.",
      },
    ];

    await db.insert(courseSessions).values(sessions);
  }

  // 5. Game Scores (Leaderboard)
  await db.insert(gameScores).values([
    {
      playerName: "هکر امیر (رکوردساز)",
      score: 18450,
      levelReached: 6,
      coinsCollected: 142,
    },
    {
      playerName: "سایبر نینجا",
      score: 14200,
      levelReached: 5,
      coinsCollected: 98,
    },
    {
      playerName: "کد نویس شب",
      score: 11900,
      levelReached: 4,
      coinsCollected: 76,
    },
    {
      playerName: "نوازنده دیجیتال",
      score: 8750,
      levelReached: 3,
      coinsCollected: 52,
    },
    {
      playerName: "مهندس رضا",
      score: 6400,
      levelReached: 2,
      coinsCollected: 38,
    },
  ]);

  // 6. Notifications
  await db.insert(notifications).values([
    {
      title: "به وب‌سایت دیجیتالیست خوش آمدید!",
      message: "پلتفرم رسمی هکر امیر در زمینه تکنولوژی، سخت‌افزارهای نو و آموزش‌های تخصصی رونمایی شد.",
      link: "/",
      type: "info",
    },
    {
      title: "تخفیف ویژه دوره‌های آموزشی تا ۲۵٪",
      message: "به مناسبت افتتاحیه، کلیه دوره‌های فتوشاپ، پریمیر، پایتون و ویولن دارای تخفیف استثنایی هستند.",
      link: "/courses",
      type: "discount",
    },
    {
      title: "مسابقه بازی Digitalist Runner",
      message: "با ثبت رکورد بالا در بازی دوبعدی ما، در تابلوی امتیازات برتر قرار بگیرید!",
      link: "/game",
      type: "course",
    },
  ]);

  // 7. Initial Reviews
  await db.insert(reviews).values([
    {
      itemType: "product",
      itemId: 1,
      authorName: "سامان کمالی",
      rating: 5,
      comment: "کیس تایتان دیجیتالیست فوق‌العاده‌ست! اسمبل بسیار تمیز و بی سر و صدا، رندر پریمیر که قبلاً ۳ ساعت طول می‌کشید الان زیر ۱۰ دقیقه تموم می‌شه.",
      isApproved: true,
    },
    {
      itemType: "product",
      itemId: 7,
      authorName: "مهتاب شریفی",
      rating: 5,
      comment: "ویولن استرادیواری که خریدم بسیار ساز خوش‌دستیه. رگلاژ و صدای ساز دقیقاً همان چیزی بود که امیر عزیز توضیح داده بودند. ممنونم از پشتیبانی عالی.",
      isApproved: true,
    },
    {
      itemType: "course",
      itemId: 1,
      authorName: "آرمان نژادی",
      rating: 5,
      comment: "دوره فتوشاپ هکر امیر فوق‌العاده کاربردیه. هیچ وقت فکر نمی‌کردم ابزارهای هوش مصنوعی و ماسک‌ها رو به این روانی متوجه بشم.",
      isApproved: true,
    },
    {
      itemType: "course",
      itemId: 4,
      authorName: "نیلوفر باقری",
      rating: 5,
      comment: "آموزش متد سوزوکی با ویولن به شدت با حوصله و شیوا توضیح داده شده. تمرینات آرشه‌کشی ویدیویی خیلی به تصحیح دستم کمک کرد.",
      isApproved: true,
    },
  ]);

  return { status: "success" };
}
